harness_platform_account_id = "Io9SR1H7TtGBq9LVyJVB2w"
organization_prefix         = "cristian-lab-infrateam-org"

harness_platform_projects = {
  "aws-eks-tf" = {
    enable      = true
    description = "Project generated by terraform harness provider"
  }
  "aws-ec2-tf" = {
    enable      = true
    description = "Project generated by terraform harness provider"
  }
}
