harness_platform_account_id = "Io9SR1H7TtGBq9LVyJVB2w"
organization_prefix         = "cristian_lab_infrateam_org"

remote_state = {
  backend = "gcs"
  config = {
    bucket = "crizstian-terraform"
    prefix = "cristian_lab_devsecops_org"
  }
}

harness_platform_projects = {
  "hashicorp_stack_gcp" = {
    enable      = true
    description = "Project generated by terraform harness provider"
    tags        = ["team: cloud"]
  }
  "hashicorp_stack_aws" = {
    enable      = true
    description = "Project generated by terraform harness provider"
    tags        = ["team: cloud"]
  }
  /* "aws-ecs-tf" = {
    enable      = true
    description = "Project generated by terraform harness provider"
    tags        = ["owner: movie-service-app"]
  }
  "aws-nomad-tf" = {
    enable      = true
    description = "Project generated by terraform harness provider"
    tags        = ["owner: movie-service-app"]
  }
  "aws-ec2-tf" = {
    enable      = true
    description = "Project generated by terraform harness provider"
    tags        = ["owner: security-team"]
  }
  "aws-network-tf" = {
    enable      = true
    description = "Project generated by terraform harness provider"
    tags        = ["owner: infrateam"]
  } */
}
