harness_platform_pipelines = {
  packer_hashistack_gcp = {
    project_ref = "hashicorp_stack_gcp"
    components = {
      pipeline = {
        enable      = true
        description = "Pipeline generated by terraform harness provider"
        file        = "templates/dev/pipelines/packer-hashistack-gcp.tpl"
        tags        = ["component: packer", "cloud: gcp"]
        stages = {
          /* terraform_sto_stage = {
            template_stage = true
            version        = "beta"
          } */
        }
        vars = {
          approver_ref  = "account.SE_Admin"
          git_connector = "infrateam_account"
        }
      }
      inputset = {
        gcp = {
          enable      = true
          file        = "templates/infrateam/inputsets/seed_tf_sto_inputset.tpl"
          description = "Inputset generated by terraform harness provider"
          tags        = ["component: packer"]
          vars = {
            git_repo         = "learn-nomad-cluster-setup"
            docker_connector = "shared_services"
            GCP_PROJECT_ID   = "sales-209522"
            GCP_REGION       = "us-central1"
            GCP_ZONE         = "us-central1-a"
          }
        }
      }
      trigger = {
        /* github = {
          enable      = false
          tags        = ["component: seed_setup"]
          file        = "templates/infrateam/triggers/devsecops.tpl"
          description = "Trgger generated by terraform harness provider"
          inputset_ref = {
            "apply" = true
            "sto"   = true
          }
          vars = {}
        } */
      }
    }
  }
}
